### ISSUE TITLE
rearrangements between two branches?

### ISSUE THREAD

**Issue by mahulchak** [glennhickey/hal#33]
Hello,
I am using halBranchMutations to obtain a list of mutations (SVs and SNPs) between different genomes provided in the example. The current documentation on the command says "To generate tables of rearrangement mutations between human and its most recent ancestor in the alignment, run"... 

I am slightly confused here. what if I am trying to obtain a list of rearrangements between human and chimp? How would I specify that I am trying to obtain the mutations between human and chimp and not human and gorilla?

Thank you.
Mahul

**Comment by glennhickey** [comment]
That command will only works branch by branch, currently.  Human and chimp
are (presumably) separated by two branches (human-chimp-ancestor --> human
and human-chimp-ancestor --> chimp).  The rearrangements between the human
and chimp will be the union of the sets of rearrangements on these two
branches, obtained by running halBranchMutations on both human and chimp.
Gorilla should not come into play here.

Unfortunately, the rearrangements you get by doing this will be outputted
in bed files in different coordinate systems for the different species,
which will probably be an issue.  halLiftover may be of use to consolidate
them.

Note you can visualize rearrangements between human and chimp on the
browser:

http://bioinformatics.oxfordjournals.org/content/30/23/3293.short

On the command line, you can do something analgous by just using
halLiftover to map chromosomes from human to chimp, and using the bed (or
psl) output to deduce breakpoints.

Getting a better command-line interface for all this is certainly an
interesting area for further development, as I agree it's quite lacking in
the present state...

**Comment by mahulchak** [comment]
I see. That is very helpful to know. I will try liftover on the
rearragement coordinates.

**Comment by mahulchak** [comment]
Hi Glenn,

Many thanks for patiently answering my previous questions. Now I have some
fresh ones.

I generated alignments between two insect species (species1 and species2)
genomes using progressiveCactus. I am specifically looking for genes that
are single copy in species 1 but got duplicated in species 2. So I used
 halBranchMutations to obtain list of duplicates between species2 and Anc0
(these seem to be reported in the --parFile ). However, it seems
halBranchMutations is reporting too many duplication events. My questions
are -

1) Do these coordinates based on ancestral coordinates represent the
coordinates of the single copy parent gene?

2) If they indeed represent coordinates of the parent genes, is there a way
to know the coordinates of the duplicated genes (e.g. how do I know which
are retroduplicated and which are tandem duplicates)?

3) Am I interpreting the "duplication" events incorrectly with respect to
ancestral and child genome? Do these "duplication" events reported between
Anc0 and species2 not represent the genes that are single copy in species1
but duplicated in species 2?

Thank you.
Mahul

**Comment by glennhickey** [comment]
These are great questions.  And may be a bit confounded by the fact that
cactus can be rather aggressive when calling duplications (depending on the
options -- this is an area that's being developed alot).  So you may get
lots of little duplications that you don't really care about (if you
suspect that, please raise an issue on the progressive cactus github).

But anyway, I think I would lean toward using halLiftover here.
 halBranchMutation will just give you regions in the ancestor that have
more than one descendant in the given species (with no idea of copy
number).  Lifting a bed corresponding to a single copy gene in one species
1 to species 2, should give you an idea of all the rearrangements for that
gene in a more usable form.

hope that's of some help -- thanks for your partience!
