### ISSUE TITLE
phyloP BED12 format

### ISSUE THREAD

**Issue by evolgenomology** [glennhickey/hal#45]
Hi!

Running the phyloP pipeline I am getting the following error:
halPhyloPTrain.py ProgCact_run2.hal schizPom Schizosaccharomyces_pombe.ASM294v2.22.cds.gff2bed halPhyloPTrain.ProgCact_run2.1.mod --numProc 12
hal exception caught: Only compatible with BED12 input. 4d sites are sensitive to frame. Even if your genes are all single-exon, please convert them to BED12 first. -- input bed line 1
Traceback (most recent call last):

I tried to modify my bed file into the 12 field format using bedops (gff2bed) and some awk, but the error persists.
I       0       5662    CDS:SPAC212.11.1:pep    .       -       .       CDS     0       ID=CDS:SPAC212.11.1:pep;Parent=transcript:SPAC212.11.1  .       .
I       12157   12994   CDS:SPAC212.08c.1:pep   .       +       .       CDS     0       ID=CDS:SPAC212.08c.1:pep;Parent=transcript:SPAC212.08c.1        .       .
I       15854   16226   CDS:SPAC212.12.1:pep    .       +       .       CDS     0       ID=CDS:SPAC212.12.1:pep;Parent=transcript:SPAC212.12.1  .       .
I       18071   18306   CDS:SPAC212.06c.1:pep   .       +       .       CDS     0       ID=CDS:SPAC212.06c.1:pep;Parent=transcript:SPAC212.06c.1        .       .
I       18348   18557   CDS:SPAC212.06c.1:pep   .       +       .       CDS     2       ID=CDS:SPAC212.06c.1:pep;Parent=transcript:SPAC212.06c.1        .       .

Any help with this would be highly appreciated.

Philipp

**Comment by glennhickey** [comment]
The BED parser as it stands is fairly strict when it comes to types, and
expects the input to closely follow the format here:

https://genome.ucsc.edu/FAQ/FAQformat.html#format1
ex: chr22 2000 6000 cloneB 900 - 2000 6000 0 2 433,399, 0,3601

In particular, it won't accept "." or arbitrary strings in the numeric
numeric fields.  So in order to use it, you will have to lump all your
metadata into, say, the name column (4), and provide valid block
information for each line (could be a single block that's identical to the
chromStart / chromEnd)

On Mon, Jun 27, 2016 at 11:53 AM, Philipp Schiffer <notifications@github.com

**Comment by evolgenomology** [comment]
Hi!

Thanks for your reply. I am still having troubles with this though - maybe I am stupid?
I converted to this now:
I       0       5662    CDS:SPAC212.11.1:pep    0       -       0       5662    0       1       0       5662
I       12157   12994   CDS:SPAC212.08c.1:pep   0       +       12157   12994   12157   1       12157   12994

Which gave:
```
halPhyloPTrain.py ProgCact_run2.hal schizPom Schizosaccharomyces_pombe.ASM294v2.22.cds.gff2bedtrue12.3 halPhyloPTrain.ProgCact_run2.1.mod --numProc 12
Line 1, block 0: BED coordinates invalid
hal exception caught: Error BED block out of range -- input bed line 2
```

So, I realised BED must start counting at 1 (not 0). Therefore, I tried:
I       1       5662    CDS:SPAC212.11.1:pep    0       -       0       5662    0       1       0       5662
I       12157   12994   CDS:SPAC212.08c.1:pep   0       +       12157   12994   12157   1       12157   12994

However, this gave:

```
halPhyloPTrain.py ProgCact_run2.hal schizPom Schizosaccharomyces_pombe.ASM294v2.22.cds.gff2bedtrue12.3 halPhyloPTrain.ProgCact_run2.1.mod --numProc 12
hal exception caught: Only compatible with BED12 input. 4d sites are sensitive to frame. Even if your genes are all single-exon, please convert them to BED12 first. -- input bed line 1
Traceback (most recent call last):
```

Could you maybe point me towards a correct format with an example based on my two BED lines?

Cheers

Philipp

**Comment by glennhickey** [comment]
For the BED specification and working examples, again, please read here

https://genome.ucsc.edu/FAQ/FAQformat.html#format1

Note in particular:
*2. chromStart* - The starting position of the feature in the chromosome or
scaffold. The first base in a chromosome is numbered 0.
*11. blockSizes* - A comma-separated list of the block sizes. The number of
items in this list should correspond to *blockCount*.
*12. blockStarts* - A comma-separated list of block starts. All of the
*blockStart* positions should be calculated relative to *chromStart*. The
number of items in this list should correspond to *blockCount*.

So to fix your lines:

I 0 5662 CDS:SPAC212.11.1:pep 0 - 0 5662 0 1 5662 0
I 12157 12994 CDS:SPAC212.08c.1:pep 0 + 12157 12994 12157 1 837 0

**Comment by evolgenomology** [comment]
Hi!

Thanks a lot. This works. However, there is a downstream error. Opening a new issue for this.

P
