### ISSUE TITLE
Odd HAL handling of EnsEMBL MAFs

### ISSUE THREAD

**Issue by CDieterich** [glennhickey/hal#50]
Dear developer,

I encountered a confusing behaviour of HAL with Ensembl MAF files
see attached maf file
[very_small.maf.txt](https://github.com/glennhickey/hal/files/441920/very_small.maf.txt)

If I run  maf2hal very_small.maf small.hal
everything seems fine

but if I want to extract maf again, I get something very different:

I would expect (from very_small.maf):

a
s homo_sapiens.2                     629356   21392 +  242193529 GCAGAATTTAAAATA
s pan_troglodytes.2A                 619768   21180 +  113622374 GCAGAATTTAAAATA
s gorilla_gorilla.2a                 628232   22420 +  111351968 GCAGAATTTAAAATA
s pongo_abelii.2a                    626026   26257 -  113028656 GCAGAATTTAAAATA
s chlorocebus_sabeus.14              572335   21694 -  107702431 GCAGAATTTAAAATA
s papio_anubis.13                    560811   21646 +  128036923 GCAGAATTTAAAATA
s callithrix_jacchus.14              678752   17020 -  108792865 GCAGAATTTAAAATA

but I get
hal2maf --refGenome homo_sapiens --refSequence 2 --start 629356 --length 16 small.hal stdout
a
s       homo_sapiens.2  629356  16      +       242193529       GCAGAATTTAAAATAA
s       callithrix_jacchus.14   695717  16      -       108792865       TCTTCTGCTCAAAGTC
s       chlorocebus_sabeus.14   593974  16      -       107702431       TCTTCTGCTTGAAGCC
s       gorilla_gorilla.2a      628232  16      +       111351968       GCAGAATTTAAAATAA
s       pan_troglodytes.2A      619768  16      +       113622374       GCAGAATTTAAAATAA
s       papio_anubis.13 560811  16      +       128036923       GCAGAATTTAAAATAA
s       pongo_abelii.2a 652228  16      -       113028656       TCTTCTGCTTGAAGCC

Any ideas ?

**Comment by glennhickey** [comment]
Looking like that, it would seem there's a bug in maf2hal's support for
reverse strand blocks.  I'll try to look into it when I have a chance...

**Comment by CDieterich** [comment]
Ok, thanks.
Would you know of any substitute in the meantime.
UCSC mafs should or should not work ?

Cheers

**Comment by glennhickey** [comment]
The thing is, we generally output HAL directly with Cactus without ever
running maf2hal.  So I'm worried maf2hal got broken without being noticed,
and I'm not sure any MAF is going to work.  Will try to verify this today.

**Comment by CDieterich** [comment]
Oh I see. Thank you for looking into this.
My main motivation for using HAL is to get fast and seamless
access to whole genome alignments of primates and vertebrates.
However, I do not have the compute capacity to compute MAF/Cactus alignments from scratch.

**Comment by glennhickey** [comment]
OK, this should hopefully be fixed now.

Thanks for your patience, and for the clear example!

**Comment by CDieterich** [comment]
Ok, after running
mafStrander --maf pruned.maf --seq homo_sapiens --strand + > positive.maf
to put the reference species on the '+' strand. Everything seems to work.
Thank you !
